### ISSUE TITLE
High CPU usage / lagging when mouse cursor is on 'root window' / desktop background

### ISSUE THREAD

**Issue by grooveharder** [riverwm/river#446]
Hi, I am new to river / wayland so apologies for an inaccuracies in terminology.

I am testing this with the proprietary NVIDIA driver and river works pretty well. Firefox, foot terminal and Xwayland seem to be functioning. However when I move the mouse on the root window (default blue background) it is extremely laggy and htop reports river's CPU usage to shoot up.

Is there anything I can do to debug this? I'm using the latest git version on Arch Linux.

Cheers,
Rob

**Comment by Leon-Plickat** [comment]
You are definitely not using river with the proprietary nvidia drivers. They are completely unsupported in wlroots and will simply not work. River therefore either runs on integrated graphics, or using software rendering (which might explain the high CPU usage you report).

Could you provide some logs please?

---

BTW there is no "root window" as Wayland does not share the rooted window tree of X.

**Comment by ryndinol** [comment]
I think I have the same issue, high CPU usage when wiggling the mouse cursor on an empty background.
![image](https://user-images.githubusercontent.com/2739611/135949118-e2d80522-1dbc-4bb1-89ad-780458e17cd9.png)

Using amdgpu, don't see anything strange in the logs.
[log.txt](https://github.com/ifreund/river/files/7282236/log.txt)

**Comment by ryndinol** [comment]
Output of perf (`perf record -F 99 -p 1042 -g -- sleep 30`)

![](https://gist.github.com/ryndinol/260c167f733784e23e1f13ca8d5bd07c/raw/perf.svg)
[perf.data.tar.gz](https://github.com/ifreund/river/files/7282391/perf.data.tar.gz)

**Comment by grooveharder** [comment]
You're right, it seems to be running on nvidia-drm but some interfaces aren't support (although, it does run pretty well, except the issue I'm describing). If I run river with the WLR_RENDERER_ALLOW_SOFTWARE environment variable, the performance is way worse. The log below is without that variable.

[river.log](https://github.com/ifreund/river/files/7287937/river.log)

**Comment by ifreund** [comment]
@grooveharder as it says in that log, your proprietary nvidia driver does not support the required interfaces and wlroots falls back to the pixman based software renderer instead. This is different from the EGL software rendering you would get with `WLR_RENDERER_ALLOW_SOFTWARE` as pixman is much more efficient.

Proprietary nvidia drivers are not officially supported by river and never will be. They may eventually start working if nvidia finally implements the standard interfaces all other drivers support, but even then we will not accept proprietary-driver-specific bug reports.

Since river isn't running on the nvidia drivers here though, the issue reported here is unrelated to them and valid.

**Comment by ifreund** [comment]
I looked into this a bit today and suspect the reason river's performance here is not as good as e.g. sway's is because river does not yet implement full damage tracking (See #206). I can reproduce the same issue with wlroots 0.14.1 tinywl (which implements no damage tracking at all).

Rather than spend time debugging this now, I intend to wait for wlroots 0.15.0 to release with `wlr_scene` and use `wlr_scene` to bring full damage tracking to river, which should resolve this issue.

**Comment by ifreund** [comment]
Ended up fixing this in f2fc9aca183dc4e724826660b79fe0d7b9103d27
