### ISSUE TITLE
Honor set_fullscreen requests made before xdg toplevels are mapped

### ISSUE THREAD

**Issue by bg2908** [riverwm/river#480]
Kodi alway open with black screen and window mode in river.

Beside that the app seem to load and work normally. You can choose item and hear sound feedback in background. Open movie give you sound and app window start to blink.

I only have this problem in river. In GNOME or sway, it work fine.

**Comment by ifreund** [comment]
Actually this is a kodi bug, not a river bug. What's happening here is that kodi requests that its window be made fullscreen instantly on creation and fails to behave correctly if the compositor does not honor that request. The wayland protocol allows compositors to ignore fullscreen requests for whatever reason they choose, so kodi must handle this.

That said, there's no real reason river shouldn't be able to honor requests in this case, it's just a bit of missing code.

**Comment by bg2908** [comment]
Confirm that there is no black screen when open Kodi with window mode on by default. And you can toggle fullscreen after the app successfully start.

**Comment by martinetd** [comment]
I've open https://github.com/xbmc/xbmc/issues/20629 to investigate the kodi side of it a bit.

From a quick look it looks like it is more of a sequence issue, kodi expects the window size to come back during its initialization and fails to setup properly if it doesn'trather quickly when the window is initialized come back then, even if it'd normally handle later configure events (the way it's handled is different later on).
The problem with later events is that they handle them as batches after every frame, but since nothing is displayed the commit never comes and the configure is never processed and... well... kodi needs to wait a bit longer for further configure events if the first one doesn't have a size.

This all comes back down to the fact that writing wayland clients from scratch is hard...

Anyway, I'll probably have a patch ready in a bit

**Comment by martinetd** [comment]
So I had this waiting for configure not processed right, but not the reason why it wasn't processed, which is silly (the event handling loop in the kodi application code ignores window resizes if this is fullscreen, but two internal "are we fullscreen?" state didn't agree so the wayland code sent the wrong event there instead of another one that wouldn't have been ignored)

Unfortunately that doesn't mean the fix is straightforward.
I've sent a patch in https://github.com/xbmc/xbmc/pull/20632 , but I'm not sure it'll be taken as is as I had to change something in the common part of the windowing code... We'll see how this goes.

Anyway, probably not going to have much more to say here - please follow the PR if interested.

**Comment by ifreund** [comment]
Implemented in 096e175ceca0b0ce313da58cd2d00b189f5ac458
