### ISSUE TITLE
error: ConnectFailed

### ISSUE THREAD

**Issue by NiceStuff2Code** [riverwm/river#522]
I got the following error if i run riverctl.
I installed the wm with the AUR.
Maybe i missed something..

The main problem is that i cann't do anything with my keyboard if i run river.

![IMG_20220130_155037.jpg](https://user-images.githubusercontent.com/34421646/151704765-70af1159-45f5-40a4-9f73-f8b6e86a51fa.jpg)

**Comment by Leon-Plickat** [comment]
If you just run `riverctl` fom a TTY, it does not have the necessary information to connect to river. You will need to set `WAYLAND_DISPLAY`.

However your actual problem seems to be

> The main problem is that i cann't do anything with my keyboard if i run river.

which probably means you have no `init` file. Copy `example/init` from rivers repository to `~/.config/river/init` and make sure it is executable. Than make sure you have the right terminal installed, or change the terminal in the init file to whatever terminal you'd like to use.

**Comment by NiceStuff2Code** [comment]
The main problem is that river don't know what my keyboard layout is..

I tried the following to setup my keyboard layout:
https://unix.stackexchange.com/questions/399998/how-to-use-setxkbmap-from-tty#587341
But this give me: ![IMG_20220130_160231.jpg](https://user-images.githubusercontent.com/34421646/151705200-2f827166-4c5a-4066-b8c2-581bcf015b3f.jpg)

**Comment by Leon-Plickat** [comment]
`setxkbmap` is an X utility and does not work with Wayland.

To set the keymap, you need to set the `XKB_DEFAULT_LAYOUT` env var before starting river, as described in `man river.1`.

**Comment by novakne** [comment]
Your river version is probably too old, the 'super' alias have been commited some days ago, you probably need to use the example init from before, https://github.com/riverwm/river/blob/0bdf3488836c9aad3d8fdc8f4f6433daca9a42cf/example/init

**Comment by NiceStuff2Code** [comment]
> Your river version is probably too old, the 'super' alias have been commited some days ago, you probably need to use the example init from before, https://github.com/riverwm/river/blob/0bdf3488836c9aad3d8fdc8f4f6433daca9a42cf/example/init


This fixed the main problem, thank you!

**Comment by JohannesRodt** [comment]
I have the same Issue with error: ConnectFailed when running riverctl
After exporting WAYLAND_DISPLAY=wayland-0 in my zshrc, this error still occurred.
Might not be connected, but sway outputted [swaybg-1.1.1/main.c:568] Unable to connect to the compositor. If your compositor is running, check or set the WAYLAND_DISPLAY environment variable.

**Comment by novakne** [comment]
You don't need to set WAYLAND_DISPLAY and you need to run riverctl inside a river session

**Comment by JohannesRodt** [comment]
I got the error while using riverctl inside a running river session

**Comment by JohannesRodt** [comment]
Might not be connected either but this is the error waybar prints when run
[2022-06-04 22:38:10.517] [error] Bar need to run under Wayland

This error occurred while i was using river as well. The tiling, spawning foot and the tags work

**Comment by JohannesRodt** [comment]
In the hope of providing all the information necessary:
` export XKB_DEFAULT_LAYOUT=de `
is set in .zshrc  but the layout still is qwerty

**Comment by Leon-Plickat** [comment]
Do not set `WAYLAND_DISPLAY` yourself. That env var is set by river and all processes started by it will inherit it, so that they can connect.

For the keyboard layout, make sure the env var is set when you start river.  If it is only set afterwards, it will have no effect. So if you export it in your `.zshrc`, make sure that actually gets sourced when you login.

How do you start river? If you do it from a TTY and you haven't changed your login shell, than you are likely starting it from bash / sh / dash / ... and not zsh. If you use a display manager or greetd or something alike, then you'll need either a wrapper script to set those vars or launch river via a login shell.
