### ISSUE TITLE
Unable to disable monitor output

### ISSUE THREAD

**Issue by johnk1917** [riverwm/river#540]
To keep this issue explanation short, I'll start off by explaining that I have a MacBook Pro with a dual GPU. What this does is cause wayland to detect two monitors on my setup: LVDS-1 and LVDS-2. This causes there to be two different screens whenever I take screenshots despite not having two monitors at all. The issues this cause is for occasionally, modules on waybar would spawn on the second nonexistent monitor and/or switching workspaces does not work properly whatsoever. On sway, I am able to disable this second monitor by adding in 
`output LVDS-2 disable` 
In my sway config. However, for river, I cannot find anything regarding the disabling of another monitor despite having read the manpage several times. If anyone can help me find what I'm doing wrong (if I am doing something wrong here) or add in a functionality to river which would allow me to set my default monitor to a specific one and disable the other one, that would be great.

Here is a screenshot showing this (As can be seen, two monitors are detected): 
![image](https://user-images.githubusercontent.com/96326315/153595987-fbc4b7b5-9857-46a2-a294-77298e3991b1.png)

**Comment by ifreund** [comment]
River supports the `wlr-output-management` protocol so you can use a client such as `wlr-randr` or `wdisplays` to disable the output or perform other configuration.

A better fix might be setting `WLR_DRM_DEVICES` to override wlroot's auto detection of your GPUs so that only the one you want to use is used by wlroots in the first place. See https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/docs/env_vars.md
