### ISSUE TITLE
Update river in the void repo

### ISSUE THREAD

**Issue by Dimev** [riverwm/river#541]
Not sure if this is the right place to ask, but when will river in the void repo be updated to a newer version?

1.0.0 """works""" (opens, but when the mouse is not over a window it eats cpu) for me, haven't tried the newer versions yet

**Comment by novakne** [comment]
The right place would be the void-packages repo but to answer your question, newer version of river on void is blocked because of upstream dependencies. Zig 0.9 is not in void because of LLVM13 and latest version of Wayland and Wlroots are not yet up to date too, so river needs these packages to be updated before.

**Comment by Dimev** [comment]
So it's just waiting until those get updated on void too. Hopefully that improves my general wayland experience as well.

Thanks!
