### ISSUE TITLE
Copy and Paste problem

### ISSUE THREAD

**Issue by whereswaldon** [riverwm/river#554]
I'm aware that this is a complex issue, but here goes:

I help maintain a GUI toolkit in Go called [Gio](https://gioui.org). Recently, copy and paste support stopped working for Gio applications running under `river`, though the same applications work fine under `sway`. I'm not very familiar with the wayland integration code or how the clipboard works in the wayland protocols (that's not the part of the codebase I've done much with), but I _think_ the fact that the same code succeeds in `sway` indicates that either:

- there's something wrong with the `river` copy & paste implementation
- Gio isn't handling some edge case correctly

However, I lack the expertise to diagnose this. I'd really appreciate it if someone could help me identify where the fault lies here. If you want to see the problem in action, here are some easy steps:

- Install go 1.17 (any patch version)
- `go install gioui.org/example/kitchen@latest`
- `"$(go env GOPATH)"/bin/kitchen`

Try to paste into the large text editor at the top of the program.

If you try the same thing in sway, it works.

I was testing against river `0.2.0-dev-238c393` and sway `1.7`.

I know this may very well be a Gio problem, but I'd love some help understanding it and why it only pops up in `river`. Keep up the good work!

**Comment by ifreund** [comment]
Hello, I took a quick look and this does indeed appear to be a `gio` problem or a problem somewhere in `gio`'s stack.

A useful tool for debugging wayland protocol events is setting the `WAYLAND_DEBUG=1` environment variable, which will cause all protocol messages to be logged to stderr.

For an overview of how the clipboard works on wayland, see this blog post: https://emersion.fr/blog/2020/wayland-clipboard-drag-and-drop/

In order to receive a `wl_data_offer` with the contents of the clipboard from the server, a client must first create a `wl_data_device` object. Then, when the client's window is focused or when the user copies something from another application the `data_offer` event is sent to inform the client of the clipboard's content. Finally, to receive the content of the clipboard the client the client sends the `receive` request.

This looks something like this usually (logs taken from foot):
```
[ 205343.363] wl_registry@2.global(26, "wl_data_device_manager", 3)
[ 205343.370]  -> wl_registry@2.bind(26, "wl_data_device_manager", 3, new id [unknown]@14)
[ 205343.380]  -> wl_data_device_manager@14.get_data_device(new id wl_data_device@15, wl_seat@12)
...
 [ 205356.670] wl_data_device@15.data_offer(new id wl_data_offer@4278190080)
[ 205356.673] wl_data_offer@4278190080.offer("text/plain;charset=utf-8")
[ 205356.675] wl_data_offer@4278190080.offer("text/plain")
[ 205356.677] wl_data_offer@4278190080.offer("TEXT")
[ 205356.680] wl_data_offer@4278190080.offer("STRING")
[ 205356.683] wl_data_offer@4278190080.offer("UTF8_STRING")
[ 205356.685] wl_data_device@15.selection(wl_data_offer@4278190080)
...
[1084980.519]  -> wl_data_offer@4278190080.receive("text/plain;charset=utf-8", fd 16)
```

When running `kitchen` under river, I see `kitchen` bind the `wl_data_device_manger` but it never sends the `get_data_device` request.

If I had to guess about what causes this to work in sway but not river, I'd say that river and sway likely send the`wl_registry.global` events on startup in a different order and `gio`'s code doesn't handle the order river uses properly. You certainly wouldn't be alone in having this bug, gtk3 had issues with this for a long time as well.

Hope that helps and good luck debugging!

**Comment by whereswaldon** [comment]
@ifreund Thanks very much for the detailed tips! I fixed the issue, and you were exactly right. We assumed the data_device_manager would be bound before the seat. [Fix is here](https://lists.sr.ht/~eliasnaur/gio-patches/patches/33085).

**Comment by ifreund** [comment]
> @ifreund Thanks very much for the detailed tips! I fixed the issue, and you were exactly right. We assumed the data_device_manager would be bound before the seat. [Fix is here](https://lists.sr.ht/~eliasnaur/gio-patches/patches/33085).

Excellent, looks like my comment paid off :)

**Comment by eliasnaur** [comment]
Thanks, @ifreund!
