### ISSUE TITLE
Add screenshot to readme

### ISSUE THREAD

**Issue by NicTanghe** [riverwm/river#702]
I’m not going to download a WM if I can't see how it looks.

It would be great if you have a screenshot showing functions and ram usage.
term and blur/  Rounded corners ? sub 1.1G ?

**Comment by Leon-Plickat** [comment]
How a river screenshot looks depends more on the windows you have open and less so on river itself. River doesn't really have a look: We just draw simple borders around (some) windows and that's it. Especially because right now the focus is on getting the core functionality right instead of pure eye-candy. Rivers functionality is hard to show off in a screenshot.

> ram usage

Usually slightly less than X11+WM+Compositor. Considerably less than "big" Wayland servers such as mutter or kwin. Overall low enough that there is no need to ever think or worry about it.

> term

How terminals will look in river depends on the terminal itself, not on river.

> blur

No.

>  Rounded corners

No.

> sub 1.1G

What?

---

If you *really* need to know how river looks like, [there are six screenshots at the bottom of this blog post](https://leon_plickat.srht.site/blog/setting-up-river-010/article.html). But as I said above, those show off the used applications and desktop widgets more than river itself.
