### ISSUE TITLE
spawn a command with quotes

### ISSUE THREAD

**Issue by dkwo** [riverwm/river#716]
The command
`wtype "$(grep -v '^#' ~/bookmarks | bemenu -i -l 50 | cut -d' ' -f1)"`
works fine from a terminal, but 
`riverctl map normal $mod B spawn 'wtype "$(grep -v '^#' ~/bookmarks | bemenu -i -l 50 | cut -d' ' -f1)"'`
does not, with `error(command): spawn: too many arguments`. Is there a way to make it work? Perhaps I'm not quoting correctly, in order for the spawn command to work.
Is this possible at all?
Thanks.

**Comment by NickHastings** [comment]
For such non-trivial commands it is often best to use a script. Eg
```
riverctl map normal $mod B spawn bmenu-bookmark.sh
```
Where bmenu-bookmark.sh would just contain:
```
#!/bin/bash
wtype "$(grep -v '^#' ~/bookmarks | bemenu -i -l 50 | cut -d' ' -f1)"
```

Instead of having separate helper scripts like that, I keep everything in my ~/.config/river/init and recursively call it with an argument corresponding to a function that performs the desired action.
Eg

```
!/bin/bash

function bmenu_bookmark {
  wtype "$(grep -v '^#' ~/bookmarks | bemenu -i -l 50 | cut -d' ' -f1
}

function init {
  # Nomal river init stuff here
  .
  .
  .
  riverctl map normal $mod B spawn "$0 --bmenu-bookmark"
  .
  .
  .
}

while [[ "$1" != "" ]] ; do
    case "$1" in
        --bmenu-bookmark )
            bmenu_bookmark
            exit $?
            ;;
    esac
    shift
done

init
```

This may be overkill for some people but I have about six of these more complex commands implemented as functions executed by calling "$0 --foo".

**Comment by dkwo** [comment]
The script solution is a bit cumbersome, but it works, thanks.

**Comment by NickHastings** [comment]
> The script solution is a bit cumbersome, but it works, thanks.

I agree that having separate scripts can be messy, that's why I decided to use functions inside the init script.

**Comment by dkwo** [comment]
Got it, thanks.
