### ISSUE TITLE
Option to disable applications from going into floating/fullscreen mode themselves.

### ISSUE THREAD

**Issue by alanxoc3** [riverwm/river#722]
Basically, I want all my windows to go into tile mode. I only want them to float/fullscreen if I hit my riverctl keybinding that sets that.

Here are my proposed configuration options that would be added to riverctl:

```
*allow-application-floating* *enabled*|*disabled*
	If enabled, applications can force their window to go into floating mode, this is done by setting the window to a specific size. If disabled, requests to become floating windows are only allowed if done by riverctl. Defaults to enabled.

*allow-application-fullscreen* *enabled*|*disabled*
	If enabled, applications can force their window to go into fullscreen. If disabled, requests to become fullscreen are only allowed if done by riverctl. Defaults to enabled.
```

I have time, so I am currently looking into how to add this into the codebase myself. Expect a PR soon. Feedback would be appreciated.

**Comment by Leon-Plickat** [comment]
> If enabled, applications can force their window to go into floating mode

This is not how this works. Applications have no concept of tiling or floating, as that is a concept specific to river (and of course a few others from the same niche). River merely automatically floats windows when they have a fixed size and based on a few other heuristics.

> this is done by setting the window to a specific size

Also not how this works. Unlike on X, Wayland windows **always** set their own size. The server has absolutely no control over the size the client renders its windows. The server merely controls how it is composited into the desktop scene. When the server asks the client to resize its windows, that is merely a suggestion and the client is free to ignore it.

> If enabled, applications can force their window to go into fullscreen

On Wayland applications don't "force" fullscreen. They *request* fullscreen, which the server can grant or ignore.

---

TBH I don't see any major changes to rivers windowing logic happening right now. The idea is to move all such policy into the layout generator, at which point an issue like this would concern the layout generator you use and no longer river itself.

**Comment by ifreund** [comment]
I have no plans to implement this in the proposed form. Eventually this should be possible for users to script without explicit support from the compositor process, but I don't think having this issue open is helpful to the development of river.

**Comment by alanxoc3** [comment]
Sorry for not responding for a few days....

@Leon-Plickat, that helps shed some light on how wayland is working, thanks.

Is there a github issue I can watch for moving that logic out to the layout generators?

And based on your explanation, I'd specifically like to be able to:
- deny application requests to go fullscreen, unless the request came from river.
- if an application sets a fixed size, immediately request a different size.
  - regardless, crop the the window to a certain size. it may resize or cut off parts of the application and make things look weird, but at least the window conforms to my tiling window layout.

Do you think those configurations would be possible from the layout generator side sometime in the future?

**Comment by Leon-Plickat** [comment]
> Is there a github issue I can watch for moving that logic out to the layout generators?

Unfortunately not.

> if an application sets a fixed size, immediately request a different size. 

Not a good idea. Applications with a fixed size (meaning `min_size == max_size`) likely will never respect the size requested by the server. They will just use their fixed size *again*, leading to an infinite loop. Even for clients that don't indicate any window size limits, it's usually better to respect their set size. Most applications usually have a good reason to not respect the size requested by the server, like for example enforcing a minimal windows size because the UI simply can not be displayed in an appropriate way in a smaller window.

River requests a window size according to the layout once on window-map and whenever the layout changes. This works reasonably well for most well-behaved clients. I'd argue that obsessing about windows fitting the layout perfectly at all times is wasting effort, since non-conforming windows are an edge case anyway. And as explained above, not respecting the size request may have a good reason. Often developers really do know better than the user.

I kinda get cropping, but resizing windows server-side would not result in a sane UX and requires yet another coordinate system transformation.

The protocol has not been designed yet, so I have no idea what will be possible and how.
However I can already tell you that the idea is to provide a simple interface to layout generators; We are willing to accept that our design may not support niche use cases.
