### ISSUE TITLE
Firefox rendering artifacts in floating mode

### ISSUE THREAD

**Issue by TAforever** [riverwm/river#814]
https://user-images.githubusercontent.com/52626363/227710022-470dfb0c-9a14-4a7f-8b67-43e929b971be.mp4

**Comment by ifreund** [comment]
what firefox theme are you using? have you patched gtk in any way?

**Comment by TAforever** [comment]
> what firefox theme are you using? have you patched gtk in any way?

firefox uses a gtk theme namely gruvbox-material-dark.
The issue does not reproduce in river 0.2.4 sway and hyprland.

**Comment by ifreund** [comment]
It sees likely that this is related to the wlroots scene graph code. Do any of the following options help?

* *WLR_SCENE_DEBUG_DAMAGE*: specifies debug options for screen damage related
  tasks for compositors that use scenes (available options: none, rerender,
  highlight)
* *WLR_SCENE_DISABLE_DIRECT_SCANOUT*: disables direct scan-out for debugging.
* *WLR_SCENE_DISABLE_VISIBILITY*: If set to 1, the visibility of all scene nodes
  will be considered to be the full node. Intelligent visibility canculations will
  be disabled.

In particular the WLR_SCENE_DEBUG_DAMAGE=none and WLR_SCENE_DEBUG_DAMAGE=rerender options would be good to try.

**Comment by TAforever** [comment]
> It sees likely that this is related to the wlroots scene graph code. Do any of the following options help?
> 
>     * _WLR_SCENE_DEBUG_DAMAGE_: specifies debug options for screen damage related
>       tasks for compositors that use scenes (available options: none, rerender,
>       highlight)
> 
>     * _WLR_SCENE_DISABLE_DIRECT_SCANOUT_: disables direct scan-out for debugging.
> 
>     * _WLR_SCENE_DISABLE_VISIBILITY_: If set to 1, the visibility of all scene nodes
>       will be considered to be the full node. Intelligent visibility canculations will
>       be disabled.
> 
> 
> In particular the WLR_SCENE_DEBUG_DAMAGE=none and WLR_SCENE_DEBUG_DAMAGE=rerender options would be good to try.

Yes, with these options the problem goes away.

**Comment by ifreund** [comment]
thanks, that's helpful. 

Just to be through, does this reproduce with the default gtk/firefox theme?

**Comment by TAforever** [comment]
> thanks, that's helpful.
> 
> Just to be through, does this reproduce with the default gtk/firefox theme?

yes

**Comment by ifreund** [comment]
> Yes, with these options the problem goes away.

To clarify, exactly which options make the problem go away? Does e.g. WLR_SCENE_DISABLE_VISIBILITY have any effect?

**Comment by TAforever** [comment]
> > Yes, with these options the problem goes away.
> 
> To clarify, exactly which options make the problem go away? Does e.g. WLR_SCENE_DISABLE_VISIBILITY have any effect?

WLR_SCENE_DEBUG_DAMAGE=none
WLR_SCENE_DEBUG_DAMAGE=renderer
WLR_SCENE_DISABLE_VISIBILITY=1
each of these three options solves the problem.

**Comment by ifreund** [comment]
Thanks, this is likely a bug in the wlroots scene graph visibility tracking code then.

Since I unfortunately cannot reproduce this myself it would be helpful if you were able to check if this is reproducible using wlroots 0.16.2 tinywl and wlroots master tinywl: https://gitlab.freedesktop.org/wlroots/wlroots/-/tree/master/tinywl

At that point we can confidently file an upstream bug report and hopefully get this fixed before wlroots 0.17.

Until then you could work around this bug with minimal performance impact by continuing to set WLR_SCENE_DISABLE_VISIBILITY=1.

**Comment by TAforever** [comment]
> Thanks, this is likely a bug in the wlroots scene graph visibility tracking code then.
> 
> Since I unfortunately cannot reproduce this myself it would be helpful if you were able to check if this is reproducible using wlroots 0.16.2 tinywl and wlroots master tinywl: https://gitlab.freedesktop.org/wlroots/wlroots/-/tree/master/tinywl
> 
> At that point we can confidently file an upstream bug report and hopefully get this fixed before wlroots 0.17.
> 
> Until then you could work around this bug with minimal performance impact by continuing to set WLR_SCENE_DISABLE_VISIBILITY=1.


I'm sorry, I made a stupid mistake. I usually start river with a variable export script, but when I checked I started river without the MOZ_ENABLE_WAYLAND=1 variable so that firefox was started via xwayland (facepalm). I tried again and I can say that WLR_SCENE_DEBUG_DAMAGE=none and WLR_SCENE_DEBUG_DAMAGE=renderer don't fix the problem, only the WLR_SCENE_DISABLE_VISIBILITY=1 option fixes the problem.

**Comment by TAforever** [comment]
I built tinywl master and reproduced this bug. Then I will open an issue in gitlab.

**Comment by ifreund** [comment]
Excellent, thanks!

**Comment by Nefsen402** [comment]
Hi, I'm not convinced that you are running a clean version of firefox. I run the sway scene patches on multiple systems, and along with a few other people and no one has reported anything like this. In my experience, firefox does have an easily reproducible damage tracking bug on scene, but that's only on startup. When firefox starts up, it will create a opaque surface but the surface still has an alpha channel. When starting up, and before firefox renders anything into the surface, wlroots will see a fully translucent buffer but firefox claims its opaque. It's possible that some sort of plugin used to style firefox ties to to a transparency effect but firefox is dumb and unconditionally claims the surface is always opaque.

There is an upstream bug here in firefox that I can reproduce that I haven't bothered to file because it's so trivially ignorable. Maybe there is something with your setup that makes the bug clearly manifest.

I just want you to double check this is a clean firefox environment. You can try this by running firefox with a different profile `firefox -P <profile name>`

**Comment by TAforever** [comment]
https://user-images.githubusercontent.com/52626363/227773965-a02e7726-d684-4647-b3cb-d52121e10e2c.mp4

**Comment by Nefsen402** [comment]
Please re-open this issue. There is still a bug here. The documentation needs to be updated or firefox needs to be fixed.

**Comment by ifreund** [comment]
> Please re-open this issue. There is still a bug here. The documentation needs to be updated or firefox needs to be fixed.

I've removed the problematic gtk css snippet from the wiki. I don't really plan on digging into gtk/firefox so I don't think there's anything actionable left here.
