### ISSUE TITLE
Windows resized past their minimum size don't get clipped properly

### ISSUE THREAD

**Issue by Yoris1** [riverwm/river#818]
Apps that have a minimum size (discord, ms teams) create a window that is larger than the actual tile it should be in and overlaps other tiles. I saw some similar issues, but they were all referencing wlroots issues. At this point it is not reproducible on sway, so it does not look like a wlroots issue

**Comment by Leon-Plickat** [comment]
This is expected behaviour. The layout sizes of tiled windows are treated as a hint, not as an order. Clients are free to ignore it and render at any size they consider suitable.

**Comment by vide0hanz** [comment]
@Leon-Plickat Could this expected behavior be optionally disabled by the user if desired though? Either by a global config option, or a rule-add option? We already have the ability to enforce server-side decorations, for example. I think adding the ability to enforce the tiled sizes as well would make logical sense too.
