### ISSUE TITLE
transparency broken for waybar

### ISSUE THREAD

**Issue by hexadecatrienoic** [riverwm/river#836]
i have rounded corners in my waybar config. on river 0.2.4 they look normal:
![waybar-river0 2 4](https://github.com/riverwm/river/assets/15036323/f776d60e-1736-4c99-bbae-ec1ceab084a3)

on river 0.3.0-dev.111+792d942 they look like this most of the time:
![waybar-river0 3 0-dev 111+792d942](https://github.com/riverwm/river/assets/15036323/3796aa1f-bcc7-40a0-9e9b-e852b1bb4ee3)
the black background will flicker between the wallpaper colour, black, and white.

[waybar.log](https://github.com/riverwm/river/files/11549615/waybar.log)

**Comment by Leon-Plickat** [comment]
Looking through the waybar log, seems like waybar sets an opaque region for it's surface. I am pretty sure that since moving to the scene graph, river now no longer ignores opaque regions.

Opaque regions are a way for the client (waybar) to tell the server (river) that an area is never transparent, which can be used as a hint for optimizing damage tracking.

Waybar setting an opaque region for parts of a buffer it actually renders transparency to is a waybar bug.
