### ISSUE TITLE
wlogout not shows correctly

### ISSUE THREAD

**Issue by superiums** [riverwm/river#885]
```bash
~ ❯❯❯ wlogout

(wlogout:7265): Gtk-WARNING **: 02:39:02.797: gtk_widget_size_allocate(): attempt to allocate widget with width 252 and height -14
```
after run, the wlogout view not show

only an icon of wlr/taskbar of waybar was shown. and the status i found from the tooltip was `fullscreen`. 
click the icon(waybar command is active): nothing happens.
right-click the icon(waybar comand is fullsceen): wlogout was show as a tiling window in tag 1.
right-click again: wlogout was shown as fullscreen. (wonder status)

- river : 0.2.4
- wlogout: 1.1.1
- voidLinux newest.

**Comment by ifreund** [comment]
This works correctly on river master as far as I can tell.

**Comment by superiums** [comment]
more details:
- after launch wlogout, the current view loose focus.
- if no view opened, wlogout shows correctly. else, not show.

so, it seems that wlogout  view was created and focused, and fullsceened, but with a negative heighth.

**Comment by superiums** [comment]
OS: void-linux newest.

**Comment by ifreund** [comment]
@superiums to be clear, I tested river's master branch while you reported that you are running 0.2.4 in the issue. Since I don't intend to do any more 0.2 bugfix releases and this doesn't reproduce on master branch there's nothing that needs to be done here. It should work in the upcoming 0.3.0 release.
