### ISSUE TITLE
some key binding conflict destroy other keybindings

### ISSUE THREAD

**Issue by superiums** [riverwm/river#888]
if two key bindings conflict, it normally override it, it's ok.

but i found this:
- use default init file
- add two key bindings:
`super+f11` for backlight up and `super+f12` backlight down.

as we know , super+F11 was used by default, as enter mode passthrough.

after run this config by `sh ~/.config/river/init`
i found only super+F12 works, other like super+drag, super+J/K .... almost all not work.
while check the output, there's no error reported.

version: 
- river 0.2.4
- void linux

**Comment by ifreund** [comment]
This issue is not reproducible for me on river master and I honestly don't see how the confilcts described here could possibly affect other keybindings.

If there's a way to reproduce this on river master with an exact sequence of commands rather than the current vague instructions feel free to drop a comment here and I'll take a closer look.
