### ISSUE TITLE
Question: Listen to river events?

### ISSUE THREAD

**Issue by Anachron** [riverwm/river#901]
Is it possible to listen to river events (stdout, fifo, etc) to be able to react to tag switching etc for statusbars or general hooks?

Edit: #385 is somewhat related, but not what I want.

**Comment by Anachron** [comment]
My idea would be a fifo which gets <event> <args> messages.

It would be okay for me to not recieve the full state (list of tags and their windows and their states) but to keep track of them myself.

I am only interested in mode and current tag currently anyway (this may change!).

**Comment by MaxVerevkin** [comment]
You can use [ristate](https://gitlab.com/snakedye/ristate) for this.

**Comment by Anachron** [comment]
Yep, that works. Thanks!

**Comment by Anachron** [comment]
Reopening due to IRC discussion:

>  TheAnachron  : aww, that's a pity. is ristate "future-proof" or will it be easy for a future change of river to make it useless?
>  ifreund      : as long as river doesn't break the protocols it uses it will be fine
>  ifreund      : I don't have plans to do so in the short term, and if I do in the 
>                 long term there will be no need for ristate because there will be 
>                 a better way to achieve what you want

**Comment by ifreund** [comment]
To be clear, the river-status wayland protocol that waybar, yambar, ristate, etc. is the intended and supported way to do this currently. I have long term plans that may require dropping this protocol due to architectural changes but nothing concrete at the moment. I don't think having this issue open really helps anything. There will always be a well-supported way to implement things like status bars.

**Comment by Anachron** [comment]
Fair enough, let's hope we get a more robust version of ristate in the future.
