### ISSUE TITLE
add shift-focused-tags

### ISSUE THREAD

**Issue by Rentib** [riverwm/river#907]
Is there any reason why not add shift tags to riverctl and instead use an external program such as [this one](https://gitlab.com/akumar-xyz/river-shifttags/-/tree/master)? I don't know zig, but I assume that adding this would take like 5 lines of code (cyclic shift of binary number). From what I know it is a fairly popular feature.

This could be something like
`riverctl shift-focused-tags`
followed by an integer.

**Comment by Leon-Plickat** [comment]
This "feature" is possible thanks to rivers script-ability enabled by the river-control and river-status protocols and is therefore effectively just a user-script, despite being implemented in a compiled binary executable.

As far as I am concerned, I wouldn't totally mind adding this to riverctl, however we also can't realistically add all user-scripts to riverctl, so we need to be conscious of where we draw the line, especially since rivers script-ability will only grow more flexible in the future.

**Comment by Rentib** [comment]
You are most definitely right. Some further discussion on how useful this would be is probably needed.

**Comment by michaelskyba** [comment]
Would it make sense to have these kinds of user-script features as shipped scripts in [contrib/](https://github.com/riverwm/river/tree/master/contrib)? This would make it easy for people interested in the feature to use it, while also avoiding adding further complexity to the main codebase. It would also serve as another example of how users can extend river programmatically, just like layout.c and layout.py are examples of how to create custom layouts.

**Comment by Rentib** [comment]
IMO it would make perfect sense, but I'm not riverwm contributor, so I don't know.
It could work similarly to patches for dwm, but better, because there wouldn't be a need for editing the source code and recompiling.

**Comment by Co3co** [comment]
I don't think this feature would be very useful. If you have a mode for tag management, you can access pretty much any tag you want with little effort. If anything, shifting tags would take more effort and be even slower than going directly to the desired tag.
