### ISSUE TITLE
0.2.4 compatibility with zig 0.11

### ISSUE THREAD

**Issue by freswa** [riverwm/river#919]
Hello,
I'm packaging the Arch Linux river package. Unfortunately we're currently packaging a commit instead of a release, since the last release 0.2.4 is not compatible with Zig 0.11. Otoh we're unable to provide zig 0.10 due to bootstrapping issues.
Are there plans to provide 0.2.5 with Zig 0.11 compatibility?

Thanks!

**Comment by NickHastings** [comment]
Can you clarify: in my experience 0.10 will trivially bootstrap, but 0.11 is a different story.

**Comment by daurnimator** [comment]
> Can you clarify: in my experience 0.10 will trivially bootstrap, but 0.11 is a different story.

I expect freswa is referring to:
  - Arch doesn't have zig 0.10 packaged any more, and reintroducing it just for river is non-negligible in terms of effort and maintenance.
  - Zig 0.10 requires LLVM 15 which is about to be removed

river itself already has commits for zig 0.11 support, so the resolution to this issue is simply to tag a release.

**Comment by NickHastings** [comment]
How does the arch package bootstrap zig 0.11? Or perhaps it doesn't and instead uses the wasm binary?

**Comment by daurnimator** [comment]
> How does the arch package bootstrap zig 0.11? Or perhaps it doesn't and instead uses the wasm binary?

Using the wasm path (and gcc); linking against system LLVM

**Comment by ifreund** [comment]
Here you go, hopefully I didn't screw anything up :)

https://github.com/riverwm/river/releases/tag/v0.2.5
