### ISSUE TITLE
Floating rules not working

### ISSUE THREAD

**Issue by hidayry** [riverwm/river#923]
River version 0.2.4

lswt result
1 ---- "Archive Manager" file-roller

than

I add 

riverctl float-filter-add app-id "file-roller"

But when open archive manager gnome still mode tilled, with fullscreen view not floating view.

Thanks

**Comment by ifreund** [comment]
Likely what has happened here is that the program you are using set/changed the app-id after it had already been opened. Since float rules are only applied by river at the moment views are opened.

You could use the `--watch` option of `lswt` to determine the initial app-id the program.

**Comment by MaxVerevkin** [comment]
I think it would be nice to support applying rules to views even after the initial mapping. Personally I'd love this because firefox picture-in-picture window is weird and sometimes sets some properties after the initial mapping. I understand that this is a client-weirdness and river tends to not include workarounds for client bugs. But in this case I can imagine this being useful in general, like switching between SSD and CSD depending on the title which changes during the view's lifetime.

**Comment by ifreund** [comment]
> I think it would be nice to support applying rules to views even after the initial mapping. Personally I'd love this because firefox picture-in-picture window is weird and sometimes sets some properties after the initial mapping. I understand that this is a client-weirdness and river tends to not include workarounds for client bugs. But in this case I can imagine this being useful in general, like switching between SSD and CSD depending on the title which changes during the view's lifetime.

I'd need to see some convincing use cases that aren't workarounds for client bugs and don't feel like abuse of a side channel for information that belongs in a proper protocol.
